---
- name: AppArmor Task - stat /etc/apparmor.d/usr.sbin.mysqld
  stat:
    path: "/etc/apparmor.d/usr.sbin.mysqld"
  register: apparmordstat
  tags:
  - aspects_mysql_server

- name: stat /etc/apparmor.d/disable/usr.sbin.mysqld
  when: apparmordstat.stat.exists
  stat:
    path: "/etc/apparmor.d/disable/usr.sbin.mysqld"
  register: apparmordisabledstat
  tags:
  - aspects_mysql_server


- name: AppArmor Task - Make sure /etc/apparmor.d/disable directory is present
  when: apparmordisabledstat.stat.exists == False and
        apparmordstat.stat.exists
  file:
    state: "directory"
    path: "/etc/apparmor.d/disable"
    owner: "root"
    group: "root"
    mode: "0755"
  tags:
    - aspects_mysql_server

- name: AppArmor Task - Disable Apparmor for mysql
  when: apparmordisabledstat.stat.exists == False and
        apparmordstat.stat.exists
  file:
    state: "link"
    src: "/etc/apparmor.d/usr.sbin.mysqld"
    path: "/etc/apparmor.d/disable/usr.sbin.mysqld"
  tags:
    - aspects_mysql_server

- name: AppArmor Task - remove apparmor mysql profile
  when: apparmordstat.stat.exists == True and
        apparmordisabledstat.stat.exists == False
  command: /sbin/apparmor_parser -R /etc/apparmor.d/usr.sbin.mysqld
  tags:
  - aspects_mysql_server
