---
- name: Change aspectsadmin@localhost password
  mysql_user:
    state: present
    name: aspectsadmin
    password: "{{ aspects_mysql_server_aspectsadmin_password }}"
    host: localhost
    login_user: "root"
    login_password: "{{ aspects_mysql_server_root_password }}"
    login_host: localhost
  tags:
    - aspects_mysql_server
    - aspects_mysql_server_change_aspectsadmin_password
