---
# when changing the root password
- name: Change root@localhost password
  mysql_user:
    state: present
    name: root
    password: "{{ aspects_mysql_server_root_password }}"
    host: localhost
    login_user: "{{ aspects_mysql_server_root_user }}"
    login_password: "{{ aspects_mysql_server_root_password_old }}"
    login_host: localhost
  tags:
    - aspects_mysql_server
    - aspects_mysql_server_change_root_password

- name: Change root@127.0.0.1 password
  mysql_user:
    state: present
    name: root
    password: "{{ aspects_mysql_server_root_password }}"
    host: 127.0.0.1
    login_user: "{{ aspects_mysql_server_root_user }}"
    login_password: "{{ aspects_mysql_server_root_password_old }}"
    login_host: 127.0.0.1
  tags:
    - aspects_mysql_server
    - aspects_mysql_server_change_root_password

- name: Change root@<server hostname> password
  mysql_user:
    state: present
    name: root
    password: "{{ aspects_mysql_server_root_password }}"
    host: "{{ ansible_hostname }}"
    login_user: "{{ aspects_mysql_server_root_user }}"
    login_password: "{{ aspects_mysql_server_root_password_old }}"
    login_host: "{{ ansible_hostname }}"
  tags:
    - aspects_mysql_server
    - aspects_mysql_server_change_root_password

- name: Change root@"::1" password.
  mysql_user:
    state: present
    name: root
    password: "{{ aspects_mysql_server_root_password }}"
    host: "::1"
    login_user: "{{ aspects_mysql_server_root_user }}"
    login_password: "{{ aspects_mysql_server_root_password_old }}"
    login_host: "::1"
  tags:
    - aspects_mysql_server
    - aspects_mysql_server_change_root_password