---
# file: roles/mysql/tasks/mysql-server.yml
- name: Debian - Set my.cnf template
  when: ansible_os_family ==  "Debian"
  template:
    src: "templates/my.cnf.j2"
    dest: "{{ aspects_mysql_server_cnf_location.Debian }}"
    owner: "root"
    group: "root"
    mode: "0600"
  notify: restart mysql
  tags:
    - aspects_mysql_server
    - aspects_mysql_server_mycnf

- name: RedHat - Set my.cnf template
  when: ansible_os_family ==  "RedHat"
  template:
    src: "templates/my.cnf.j2"
    dest: "{{ aspects_mysql_server_cnf_location.RedHat }}"
    owner: "root"
    group: "root"
    mode: "0600"
  notify: restart mysql
  tags:
    - aspects_mysql_server
    - aspects_mysql_server_mycnf
