---
# file: roles/mysql/tasks/mysql-server.yml

- name: Set my.cnf template
  template:
    src: "templates/my.cnf.j2"
    dest: "{{ aspects_mysql_server_cnf_path }}"
    owner: "root"
    group: "root"
    mode: "0600"
#    validate: "mysqld --defaults-file=%s --verbose --help"
  notify: restart mysql
  tags:
    - aspects_mysql_server
    - aspects_mysql_server_mycnf
