---
- name: RedHat - run mysql_install_db on initialization
  when: ansible_os_family == "RedHat" and aspects_mysql_server_init
  shell: "/usr/bin/mysql_install_db --user=mysql --force"
  register: redhatmysqlinstalldbran
  tags:
    - aspects_mysql_server

# notify waits too long to run the restart.
- name: RedHat - restart mysql after mysql_install_db is run
  when: ansible_os_family == "RedHat" and
        aspects_mysql_server_init and
        redhatmysqlinstalldbran is defined
  shell: "systemctl restart mariadb.service"
  tags:
    - aspects_mysql_server

# for the first run, assume root password is empty.
- name: create aspectsadmin user.
  when: aspects_mysql_server_init
  mysql_user:
    state: "present"
    name: "aspectsadmin"
    password: "{{ aspects_mysql_server_aspectsadmin_password }}"
    host: "localhost"
    priv: "*.*:ALL,GRANT"
  tags:
    - aspects_mysql_server

- name: Manage root users.
  when: aspects_mysql_server_init
  mysql_user:
    state: "{{ item.1.state }}"
    name: "root"
    password: "{{ aspects_mysql_server_root_password }}"
    host: "{{ item.1.hostname }}"
    login_user: "aspectsadmin"
    login_password: "{{ aspects_mysql_server_aspectsadmin_password }}"
    login_host: "localhost"
  loop: "{{ aspects_mysql_server_root_users | dictsort }}"
  tags:
    - aspects_mysql_server