---
- include_vars: "{{ ansible_os_family }}.yml"
  tags:
    - aspects_mysql_server
    - aspects_mysql_server_mycnf
#
#- include: installPackages.yml
#  tags:
#  - aspects_mysql_server

- name: manage AppArmor settings.
  when: ansible_apparmor.status == "enabled" and
        aspects_mysql_server_disable_apparmor
  import_tasks: "apparmor.yml"
  tags:
  - aspects_mysql_server

- include: initialize.yml
  when: aspects_mysql_server_init
  tags:
  - aspects_mysql_server

- include: changeAspectsadminPassword.yml
  when: aspects_mysql_server_aspectsadmin_password_change
  tags:
  - aspects_mysql_server
  - aspects_mysql_server_change_aspectsadmin_password

- name: Include manageRootUsers.yml
  when: aspects_mysql_server_root_password_change
  include: manageRootUsers.yml
  tags:
  - aspects_mysql_server
  - aspects_mysql_server_change_root_password

- include: configure.yml
  tags:
  - aspects_mysql_server

- include: manageDBandUsers.yml
  tags:
  - aspects_mysql_server