---
# tasks file for aspects_mysql_server
- include_vars: "{{ ansible_os_family }}.yml"
  when: aspects_mysql_server_enabled
  tags:
    - aspects_mysql_server
- include: installPackages.yml
  when: aspects_mysql_server_enabled
  tags:
  - aspects_mysql_server
- include: install.yml
  when: aspects_mysql_server_enabled
  tags:
  - aspects_mysql_server

- include: changeRootPassword.yml
  when: aspects_mysql_server_root_password_change
  tags:
  - aspects_mysql_server
  - aspects_mysql_server_change_root_password

- include: mysql-server.yml
  when: aspects_mysql_server_enabled
  tags:
  - aspects_mysql_server
- include: mysql-databases.yml
  when: aspects_mysql_server_enabled
  tags:
  - aspects_mysql_server
