---
# tasks file for aspects_mysql_server
- include_vars: "{{ ansible_os_family }}.yml"
  tags:
    - aspects_mysql_server
- include: installPackages.yml
  tags:
  - aspects_mysql_server
- include: install.yml
  tags:
  - aspects_mysql_server
- include: mysql-server.yml
  tags:
  - aspects_mysql_server
- include: mysql-databases.yml
  tags:
  - aspects_mysql_server