---
- name: ensure mysql_databases exist
  when: aspects_mysql_server_databases is defined
  mysql_db:
    state: present
    name: "{{ item.value.name }}"
    login_host: "localhost"
    login_user: "aspectsadmin"
    login_password: "{{ aspects_mysql_server_aspectsadmin_password }}"
    collation: "{{ item.value.collation }}"
    encoding: "{{ item.value.encoding }}"
  with_dict: "{{ aspects_mysql_server_databases }}"
  tags:
    - aspects_mysql_server
    - aspects_mysql_server_databases

- name: ensure database users exist
  when: aspects_mysql_server_users is defined
  mysql_user:
    state: "present"
    name: "{{ item.value.name }}"
    password: "{{ item.value.password }}"
    host: "{{ item.value.host }}"
    priv: "{{ item.value.priv }}"
    login_host: "localhost"
    login_user: "aspectsadmin"
    login_password: "{{ aspects_mysql_server_aspectsadmin_password }}"
  with_dict: "{{ aspects_mysql_server_users }}"
  tags:
    - aspects_mysql_server
    - aspects_mysql_server_users
