---
# file: roles/mysql/tasks/mysql-server.yml
- name: Debian - Set my.cnf template
  when: ansible_os_family == "Debian"
  template: src=my.cnf.j2 dest={{ aspects_mysql_server_cnf_location.Debian }} owner=root group=root mode=0600
  notify: restart mysql
  tags:
    - aspects_mysql_server
    - aspects_mysql_server_mycnf

- name: RedHat - Set my.cnf template
  when: ansible_os_family == "RedHat"
  template: src=my.cnf.j2 dest={{ aspects_mysql_server_cnf_location.RedHat }} owner=root group=root mode=0600
  notify: restart mysql
  tags:
    - aspects_mysql_server
    - aspects_mysql_server_mycnf

- name: Debian - Disable Apparmor for mysql
  when: ansible_os_family == "Debian"
  file: state=link src=/etc/apparmor.d/usr.sbin.mysqld path=/etc/apparmor.d/disable/usr.sbin.mysqld
  notify: remove apparmor mysql profile
  tags:
    - aspects_mysql_server
