---
# handlers file for aspects_mysql_server
- name: restart mysql
  when: aspects_mysql_server_restart_on_config_change
  service:
    name: "{{ aspects_mysql_server_service_name }}"
    state: restarted
    enabled: yes
  tags:
  - aspects_mysql_server
  - aspects_mysql_server_mycnf

- name: start mysql
  when: aspects_mysql_server_restart_on_config_change
  service:
    name: "{{ aspects_mysql_server_service_name }}"
    state: started
    enabled: yes
  tags:
  - aspects_mysql_server
  - aspects_mysql_server_mycnf

- name: stop mysql
  service:
    name: "{{ aspects_mysql_server_service_name }}"
    state: stopped
    enabled: no
  tags:
  - aspects_mysql_server
  - aspects_mysql_server_mycnf
