---
# handlers file for aspects_mysql_server
- name: restart mysql
  when: aspects_mysql_server_restart_on_config_change
  service:
    name: "{% if ansible_os_family == 'Debian' %}mysql{% elif ansible_os_family == 'RedHat' %}mariadb{% else %}mysql{% endif %}"
    state: restarted
    enabled: yes
  tags:
  - aspects_mysql_server
  - aspects_mysql_server_mycnf

- name: start mysql
  when: aspects_mysql_server_restart_on_config_change
  service:
    name: "{% if ansible_os_family == 'Debian' %}mysql{% elif ansible_os_family == 'RedHat' %}mariadb{% else %}mysql{% endif %}"
    state: started
    enabled: yes
  tags:
  - aspects_mysql_server
  - aspects_mysql_server_mycnf

- name: stop mysql
  service:
    name: "{% if ansible_os_family == 'Debian' %}mysql{% elif ansible_os_family == 'RedHat' %}mariadb{% else %}mysql{% endif %}"
    state: stopped
    enabled: no
  tags:
  - aspects_mysql_server
  - aspects_mysql_server_mycnf
