---
# handlers file for aspects_mysql_server
- name: restart mysql
  service: name={{ aspects_mysql_server_service_name }} state=restarted enabled=yes

- name: start mysql
  service: name={{ aspects_mysql_server_service_name }} state=started enabled=yes

- name: stop mysql
  service: name={{ aspects_mysql_server_service_name }} state=stopped enabled=no

- name: remove apparmor mysql profile
  command: sudo apparmor_parser -R /etc/apparmor.d/usr.sbin.mysqld